site_name: "Web3j"
site_description: "Documentation portal for the web3j Blockchain Library"
site_author: "Web3 Labs"
site_url: "https://web3j.io/"

repo_name: "web3j/web3j"
repo_url: "https://github.com/web3j/web3j"

# Copyright
copyright: "Copyright &copy; 2017-2019 Web3 Labs Ltd"

nav:
  - Quickstart: quickstart.md
  - Getting Started: getting_started.md
  - Modules: modules.md
  - Transactions: transactions.md
  - Smart Contracts: smart_contracts.md
  - Application Binary Interface: application_binary_interface.md
  - Recursive Length Prefix: recursive_length_prefix.md
  - Filters and Events: filters_and_events.md
  - Command Line Tools: command_line_tools.md
  - Management Apis: management_apis.md
  - Using Infura with Web3j: using_infura_with_web3j.md
  - Ethereum Name Service: ethereum_name_service.md
  - Contracts Supported by Web3j: contracts_supported_by_web3j.md
  - Troubleshooting: troubleshooting.md
  - Projects using Web3j: projects_using_web3j.md
  - Companies using Web3j: companies_using_web3j.md
  - Developer Guide: developer_guide.md
  - Links and Useful Resources: links_and_useful_resources.md
  - Thanks and Credits: thanks_and_credits.md

# Configuration
theme:
  name: "material"
  language: "en"
  logo: "img/logo.png"
  favicon: "img/favicon.ico"
  feature:
    tabs: true
  palette:
    primary: "white"
    accent: "deep-orange"
# Customization
extra:
  manifest: "manifest.webmanifest"
  social:
    - type: "github"
      link: "https://github.com/web3j"
    - type: "twitter"
      link: "https://twitter.com/web3labs"
    - type: "linkedin"
      link: "https://linkedin.com/in/web3labs"
extra_css:
  - "stylesheets/extra.css"

# Google Analytics
google_analytics:
  - 'UA-85710619-1'
  - 'auto'


# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.details
  - toc:
      permalink: true
      toc_depth: 3
